import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-white px-6 py-12 max-w-2xl mx-auto">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-invert text-zinc-300 space-y-6">
        <p>Last updated: June 2026</p>

        <h2 className="text-2xl font-semibold mt-8">The Service</h2>
        <p>Roastly lets you upload any screenshot, photo, text convo, meme — whatever — and receive AI-generated roasts (or uplifting comments) using Grok. You can buy one-time roast credit packs for this browser/device. There are no monthly subscriptions and no daily caps on purchased credits.</p>

        <h2 className="text-2xl font-semibold mt-8">Your Content</h2>
        <p>You own the images/screenshots you upload. By uploading, you give us permission to send the image to the Grok AI API for processing. We do not keep your images.</p>
        <p>Do not upload images of other people without their consent, illegal content, or anything that violates platform rules.</p>

        <h2 className="text-2xl font-semibold mt-8">Payments & Refunds</h2>
        <p>All sales are final. The roasts are digital and delivered instantly. If something goes wrong with a purchase, contact us and we will try to help (we can refund via Stripe in reasonable cases).</p>

        <h2 className="text-2xl font-semibold mt-8">Limits</h2>
        <p>New users get 3 free roasts total (occasionally higher during promos). After that, you can buy one-time credit packs (10 / 50 / 100 / 250 / 500 roasts). Purchased credits have no daily cap. Free and paid limits are enforced per browser + IP. We are not responsible if you clear your browser data and lose access to purchased credits.</p>

        <h2 className="text-2xl font-semibold mt-8">No Warranty</h2>
        <p>The roasts are generated by AI. They can be mean, inaccurate, or hilarious. Use at your own risk. We are not liable for any emotional damage, lost friendships, or bad decisions made after seeing your roasts.</p>

        <h2 className="text-2xl font-semibold mt-8">Abuse</h2>
        <p>We reserve the right to block users who abuse the free tier, upload illegal content, or try to game the system.</p>

        <p className="text-sm text-zinc-500 mt-12">By using Roastly you agree to these terms. Have fun, don&apos;t be an asshole (unless you bought a lot of credits).</p>
      </div>
      <Link href="/" className="inline-block mt-8 text-red-400 hover:text-red-300">← Back to Roastly</Link>
    </div>
  );
}
